### PR TITLE
🐳  Docker added

### PR DESCRIPTION
**Pull request by maguri**

### CODE REVIEW

**Comment by maguri** [comment]
Hi @artemv !

**Comment by artemv** [comment]
That's pretty cool, thanks @maguri! In my case (MacOS, docker client 17.09.0-ce, and docker server just upgraded to 17.09.1-ce) `docker-compose up --build` hanged at step `Attaching to ruby-starter-kit`, but then `docker exec -it ruby-starter-kit /bin/bash` works fine. Is that how it supposed to work?

**Comment by maguri** [comment]
Yes @artemv ,
The workflow is to build the docker container with the `docker-compose` command, and then, I open a bash to log in to the container and run there whatever I want.

If you have any improvement to add to the files please, do not hesitate to tell me or do it yourself. 👍🏻

**Comment by artemv** [comment]
Yeah I merged already, and tweaked it a bit - e.g. bumped the ruby version in Gemfile because docker config is based on 2.4.2

**Pull request merged**
